import '@radix-ui/themes/styles.css'
import './theme-config.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes'
import { Toaster } from 'react-hot-toast'

import Navbar from './components/Navbar'
import AuthProvider from './components/AuthProvider'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <AuthProvider>
          <Theme appearance="light" accentColor="crimson">
            <Navbar />
            <main className="p-7 max-w-screen-2xl mx-auto">{children}</main>
            <Toaster />
          </Theme>
        </AuthProvider>
      </body>
    </html>
  )
}
